name: Manual deploy to S3

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@master
      with:
        ref: ${{ github.event.inputs.tag }}
    - name: Sync S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
        AWS_REGION: ${{ vars.AWS_REGION }}
        SOURCE_DIR: ${{ vars.SOURCE_DIR }}
