# Copyright (c) 2026, Regents of the University of Michigan. All rights reserved.
# See LICENSE.txt for details.
name: Manual deploy to S3

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.2
      with:
        ref: ${{ github.event.inputs.tag }}
    - name: Sync S3
      uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311 # v0.5.1+
      with:
        args: --follow-symlinks --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
        AWS_REGION: ${{ vars.AWS_REGION }}
        SOURCE_DIR: ${{ vars.SOURCE_DIR }}
